### ISSUE TITLE
Script Log Parsing Needs Shared Persistence Compatibility

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/qs-governance-collector#17]
Script Log Parser only goes to the default c:\programdata\qlik\sense\log\script path. It needs to be customizable for a multinode, shared persistence deployment (ex: \\qlikshare\archive logs). 

For each scheduler in the site, a subdirectory is created and will contain the script log directory.

**Comment by goldbergjeffrey** [comment]
Resolved in #19
