### ISSUE TITLE
Error handling when audit logging not enabled for Governance QVD Generator for Qlik Sense

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-governance-collector#36]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Aeapowertools/qs-governance-collector

### Description

When audit logging is not enabled the script errors out.

Sample Script:

> 2017-08-31 12:10:46 2300 FROM [lib://ArchivedLogsFolder/usral-ltv.qliktech.com/Engine/Trace/*_Audit_Engine*.log]  
> 2017-08-31 12:10:46 2301 (txt, utf8, embedded labels, delimiter is '\t', msq)
> 2017-08-31 12:10:46      Error: Cannot open file: 'lib://ArchivedLogsFolder/usral-ltv.qliktech.com/Engine/Trace/*_Audit_Engine*.log'
> 2017-08-31 12:10:46      Execution Failed
> 2017-08-31 12:10:46      Execution finished.

Potential fix / work-around: SET ErrorMode=0; on line 3 of **Audit and Usage** section of the script and SET ErrorMode=1; on line 58 

### Steps to Reproduce

N/A

**Expected behavior:** N/A

**Actual behavior:** N/A

**Reproduces how often:** N/A

### Versions

N/A

### Additional Information

N/A

**Comment by rmterenzi** [comment]
Fixed

**Comment by goldbergjeffrey** [comment]
@rmterenzi, is the fix in the 1.0.1 release? Please submit your changes by creating a branch, modifying the files, commiting the changes and issuing a pull request.

Thank you!
