### ISSUE TITLE
Boxplot and Histogram coded as extensions

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-governance-collector#37]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Aeapowertools/qs-governance-collector

### Description

With the 2 new (enigma based) visualizations in the June 2017 release, they are coded as extensions on the **Usage** sheet of the Governance Dashboard for Qlik Sense app.

**Fix:**
Change the Native Objects Map inline table on **Mappings and Sorts to:**

> [Native Objects Map]:
Mapping
LOAD * INLINE [
    Object Type, Native
    barchart, Native Object
    combochart, Native Object
    filterpane, Native Object
    gauge, Native Object
    kpi, Native Object
    linechart, Native Object
    map, Native Object
    piechart, Native Object
    pivot-table, Native Object
    scatterplot, Native Object
    table, Native Object
    text-image, Native Object
    treemap, Native Object
    listbox, Native Object
    boxplot, Native Object
    Distribution plot, Native Object
    histogram, Native Object    
];

**Comment by rmterenzi** [comment]
Fixed

**Comment by goldbergjeffrey** [comment]
@rmterenzi, is the fix in the 1.0.1 release? Please submit your changes by creating a branch, modifying the files, commiting the changes and issuing a pull request.

Thank you!
