### ISSUE TITLE
Application File Size visualization on Applications sheet has wrong measure

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-governance-collector#38]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Aeapowertools/qs-governance-collector

### Description

Application File Size visualization on Applications sheet has wrong measure:

![image](https://user-images.githubusercontent.com/23237561/29937228-e0ca0ca6-8e52-11e7-9979-cd6042b0628c.png)

**Fix:** Swap the measures. The correct one is already there.

**Comment by rmterenzi** [comment]
I've fixed this

**Comment by goldbergjeffrey** [comment]
@rmterenzi, is the fix in the 1.0.1 release?  Please submit your changes by creating a branch, modifying the files, commiting the changes and issuing a pull request.

Thank you!
