### ISSUE TITLE
Library Connection Name doesn't capture non-folder data connections

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-governance-collector#40]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Aeapowertools/qs-governance-collector

### Description

Ever since 3.1.x, non folder data connections are obscured in the logs. Sample:
2017-05-09 07:00:56 0461 CALL qrs_userAccess
2017-05-09 07:00:56 0462 
2017-05-09 07:00:56 0482 LIB CONNECT TO ***

In order to grab this info you'll need to use the Engine API to grab the scripts then parse on that.

### Steps to Reproduce

1. Setup a scheduled task to run against SF / REST / ODBC / etc
2. Reload the Extract and Load apps
3. Notice they aren't there

**Reproduces how often:** 101%

### Versions

Qlik Sense Governance Collector: 1.0.1.0
Qlik Sense: June 2017 Patch 1
OS: Windows 7 Professional

**Comment by goldbergjeffrey** [comment]
Issue is one with Qlik script log generation.  Case will need to be opened with Qlik support to resolve.
