### ISSUE TITLE
Beta installer agent not starting

### ISSUE THREAD

**Issue by rvspt** [eapowertools/qs-governance-collector#74]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Aeapowertools/qs-governance-collector

### Description

Trying to import resources from GUI is not working. Looking into the agent via command line the following is thrown:

C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCollector\agent>"C:\Program F
iles\Qlik\Sense\EAPowerTools\PowerToolsServiceDispatcher\node\node.exe" server.j
s
C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCollector\agent\lib\uploadApp
s.js:46
        taskName: appInfo[0].taskName,
                             ^

TypeError: Cannot read property 'taskName' of undefined
    at C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCollector\agent\lib\up
loadApps.js:46:30
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCo
llector\agent\lib\uploadApps.js:37:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCo
llector\agent\routes.js:13:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

C:\Program Files\Qlik\Sense\EAPowerTools\GovernanceCollector\agent>

### Steps to Reproduce

1. Install
2. Launch GUI URL
3. Add new server and select "import resources" -> first issue
4. run server.js via command line -> error stated above

**Expected behavior:** 
Resources to be imported and agent running

**Actual behavior:** 
Agent unable to start

**Reproduces how often:** 
Always

### Versions
- qs-governance-dashboard_212Beta.exe
- agent: 2.1.2.0
- webapp: 2.1.2.0

- Windows 2012 R2, Qlik Sense November 2017
You can get this information by looking on the version page for the web app, agent or the config.js file located in the config directory of the distribution. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by goldbergjeffrey** [comment]
Resolved...Issue was missing files and the addition of the accessaudit.qvf breaking the uploadapps.js module because no entry made in package.json.
